node:
    build: .
    command: "node server.js"
    ports:
        - "1111:80"
    environment:
        PORT: 27017
    links:
        - mongo
    volumes:
        - $PWD/attr_data:/data
    restart: always
mongoexpress:
    image: mongo-express:latest
    ports:
        - "10080:8081"
    links:
        - mongo
    volumes:
        - /etc/ssl/private/servercerts/:/usr/certs
    environment:
        ME_CONFIG_MONGODB_SERVER: mongo
        ME_CONFIG_MONGODB_PORT: 27017
        #ME_CONFIG_BASICAUTH_USERNAME: "CHANGEME!!!"
        #ME_CONFIG_BASICAUTH_PASSWORD: "CHANGEME!!!"
        ME_CONFIG_SITE_BASEURL: "/dashboard/"
        ME_CONFIG_SITE_SSL_ENABLED: "true"
        ME_CONFIG_SITE_SSL_CRT_PATH: "/usr/certs/STAR_cbs_dtu_dk.crt"
        ME_CONFIG_SITE_SSL_KEY_PATH: "/usr/certs/STAR_cbs_dtu_dk-private.nopass.key"
    restart: always
mongo:
    ports:
        - "5999:27017"
    image: mongo
    volumes:
        - $PWD/geo_data:/usr/geodata
        - $PWD/attr_data:/usr/attrdata
        - $PWD/db:/data/db
    restart: always
notebook:
    ports:
        - "4434:8888"
    image: jupyter/datascience-notebook
    user: root
    environment:
        NB_UID: 1003
        GRANT_SUDO: "yes"
    links:
        - mongo
    volumes:
        - $PWD/notebooks:/home/jovyan/work
    restart: always
