node:
    build: .
    command: "node server.js"
    ports:
        - "5000:80"
    environment:
        PORT: 27017
    links:
        - mongo
    volumes:
        - $PWD/backend/web:/code/backend/web
        - $PWD/backend/time_series:/code/backend/time_series
mongoexpress:
    image: knickers/mongo-express
    ports:
        - "8081:8081"
    links:
        - mongo
    environment:
        ME_CONFIG_MONGODB_SERVER: mongo
        ME_CONFIG_MONGODB_PORT: 27017
mongo:
    ports:
        - "5999:27017"
    image: mongo
    volumes:
        - $PWD/geo_data:/usr/geodata
        - $PWD/attr_data:/usr/attrdata
        - $PWD/db:/src
        - ./noSQL_database/mongod:/data
