node:
    build: .
    command: "node server.js"
    ports:
        - "1111:80"
    environment:
        PORT: 27017
    links:
        - mongo
    volumes:
        - $PWD/attr_data:/data
        # - $PWD/backend:/code/backend
        # - $PWD/backend/time_series:/code/backend/time_series
mongoexpress:
    image: mongo-express
    ports:
        - "8081:8081"
    links:
        - mongo
    environment:
        ME_CONFIG_MONGODB_SERVER: mongo
        ME_CONFIG_MONGODB_PORT: 27017
        ME_CONFIG_BASICAUTH_USERNAME: "root"
        ME_CONFIG_BASICAUTH_PASSWORD: "test"
mongo:
    ports:
        - "5999:27017"
    image: mongo
    volumes:
        - $PWD/geo_data:/usr/geodata
        - $PWD/attr_data:/usr/attrdata
        - $PWD/db:/src
        - ./noSQL_database/mongod:/data
notebook:
    ports:
        - "7777:8888"
    image: jupyter/notebook
    links:
        - mongo
    volumes:
        - $PWD/notebooks:/notebooks
