#!/usr/bin/env python2.7

import csv
import os
import openpyxl
import re
import json
import sys
import pickle
import pprint
import pandas
from pymongo import MongoClient
import pprint
from sets import Set


country_code = {
    'aruba': 'ABW',
    'andorra': 'AND',
    'afghanistan': 'AFG',
    'angola': 'AGO',
    'anguilla': 'AIA',
    'albania': 'ALB',
    'arab world': 'ARB',
    'united arab emirates': 'ARE',
    'argentina': 'ARG',
    'armenia': 'ARM',
    'american samoa': 'ASM',
    'antigua and barbuda': 'ATG',
    'australia': 'AUS',
    'austria': 'AUT',
    'azerbaijan': 'AZE',
    'burundi': 'BDI',
    'belgium': 'BEL',
    'benin': 'BEN',
    'burkina faso': 'BFA',
    'bangladesh': 'BGD',
    'bulgaria': 'BGR',
    'bahrain': 'BHR',
    'bahamas, the': 'BHS',
    'bahamas': 'BHS',
    'bosnia and herzegovina': 'BIH',
    'belarus': 'BLR',
    'belize': 'BLZ',
    'bermuda': 'BMU',
    'bolivia': 'BOL',
    'bolivia (plurinational state of)': 'BOL',
    'brazil': 'BRA',
    'barbados': 'BRB',
    'brunei darussalam': 'BRN',
    'british indian ocean territory': 'IOT',
    'bhutan': 'BTN',
    'botswana': 'BWA',
    'central african republic': 'CAF',
    'canada': 'CAN',
    'central europe and the baltics': 'CEB',
    'switzerland': 'CHE',
    'channel islands': 'CHI',
    'chile': 'CHL',
    'china': 'CHN',
    'china (exc. hong kong & macao)': 'CHN',
    'china, mainland': 'CHN',
    'cote d\'ivoire': 'CIV',
    u'c\u2122te d\'ivoire': 'CIV',
    'c\xc3\xb4te d\'ivoire': 'CIV',
    'cameroon': 'CMR',
    'cocos (keeling) islands': 'CCK',
    'congo, rep.': 'COG',
    'congo': 'COG',
    'democratic republic of the congo': 'COG',
    'cook islands': 'COK',
    'colombia': 'COL',
    'comoros': 'COM',
    'cabo verde': 'CPV',
    'cape verde': 'CPV',
    'costa rica': 'CRI',
    'caribbean small states': 'CSS',
    'cuba': 'CUB',
    'curacao': 'CUW',
    'cura\xe7ao': 'CUW',
    'netherlands antilles, curacao': 'CUW',
    'christmas island': 'CXR',
    'cayman islands': 'CYM',
    'cyprus': 'CYP',
    'czech republic': 'CZE',
    'czechoslovakia': 'CSK',
    'germany': 'DEU',
    'germany fr': 'DEU',
    'djibouti': 'DJI',
    'dominica': 'DMA',
    'denmark': 'DNK',
    'dominican republic': 'DOM',
    'algeria': 'DZA',
    'east asia & pacific (developing only)': 'EAP',
    'east asia & pacific (all income levels)': 'EAS',
    'europe & central asia (developing only)': 'ECA',
    'europe & central asia (all income levels)': 'ECS',
    'ecuador': 'ECU',
    'egypt, arab rep.': 'EGY',
    'egypt': 'EGY',
    'euro area': 'EMU',
    'eritrea': 'ERI',
    'spain': 'ESP',
    'estonia': 'EST',
    'ethiopia': 'ETH',
    'ethiopia pdr': 'ETH',
    'european union': 'EUU',
    'fragile and conflict affected situations': 'FCS',
    'finland': 'FIN',
    'fiji': 'FJI',
    'falkland islands (malvinas)': 'FLK',
    'france': 'FRA',
    'faeroe islands': 'FRO',
    'faroe islands': 'FRO',
    'micronesia, fed. sts.': 'FSM',
    'micronesia (federated states of)': 'FSM',
    'gabon': 'GAB',
    'united kingdom': 'GBR',
    'united kingdom of great britain and northern ireland': 'GBR',
    'georgia': 'GEO',
    'ghana': 'GHA',
    'gibraltar': 'GIB',
    'guinea': 'GIN',
    'guadeloupe': 'GLP',
    'gambia, the': 'GMB',
    'gambia': 'GMB',
    'guinea-bissau': 'GNB',
    'equatorial guinea': 'GNQ',
    'greece': 'GRC',
    'grenada': 'GRD',
    'greenland': 'GRL',
    'guatemala': 'GTM',
    'french guiana': 'GUF',
    'guam': 'GUM',
    'guyana': 'GUY',
    'high income': 'HIC',
    'hong kong sar, china': 'HKG',
    'china, hong kong sar': 'HKG',
    'honduras': 'HND',
    'heavily indebted poor countries (hipc)': 'HPC',
    'croatia': 'HRV',
    'haiti': 'HTI',
    'hungary': 'HUN',
    'indonesia': 'IDN',
    'isle of man': 'IMN',
    'india': 'IND',
    'not classified': 'INX',
    'ireland': 'IRL',
    'iran, islamic rep.': 'IRN',
    'iran (islamic republic of)': 'IRN',
    'iraq': 'IRQ',
    'iceland': 'ISL',
    'israel': 'ISR',
    'italy': 'ITA',
    'jamaica': 'JAM',
    'jersey': 'JEY',
    'jordan': 'JOR',
    'japan': 'JPN',
    'kazakhstan': 'KAZ',
    'kenya': 'KEN',
    'kyrgyz republic': 'KGZ',
    'kyrgyzstan': 'KGZ',
    'cambodia': 'KHM',
    'kiribati': 'KIR',
    'st. kitts and nevis': 'KNA',
    'saint kitts and nevis': 'KNA',
    'korea, rep.': 'KOR',
    'republic of korea': 'KOR',
    'kosovo': 'KSV',
    'kuwait': 'KWT',
    'latin america & caribbean (developing only)': 'LAC',
    'lao pdr': 'LAO',
    'lao people\'s democratic republic': 'LAO',
    'lebanon': 'LBN',
    'liberia': 'LBR',
    'libya': 'LBY',
    'st. lucia': 'LCA',
    'saint lucia': 'LCA',
    'latin america & caribbean (all income levels)': 'LCN',
    'least developed countries: un classification': 'LDC',
    'low income': 'LIC',
    'liechtenstein': 'LIE',
    'sri lanka': 'LKA',
    'lower middle income': 'LMC',
    'low & middle income': 'LMY',
    'lesotho': 'LSO',
    'lithuania': 'LTU',
    'luxembourg': 'LUX',
    'latvia': 'LVA',
    'macao sar, china': 'MAC',
    'china, macao sar': 'MAC',
    'st. martin (french part)': 'MAF',
    'morocco': 'MAR',
    'monaco': 'MCO',
    'moldova': 'MDA',
    'republic of moldova': 'MDA',
    'madagascar': 'MDG',
    'maldives': 'MDV',
    'middle east & north africa (all income levels)': 'MEA',
    'mexico': 'MEX',
    'marshall islands': 'MHL',
    'middle income': 'MIC',
    'macedonia, fyr': 'MKD',
    'the former yugoslav republic of macedonia': 'MKD',
    'mali': 'MLI',
    'malta': 'MLT',
    'myanmar': 'MMR',
    'middle east & north africa (developing only)': 'MNA',
    'montenegro': 'MNE',
    'mongolia': 'MNG',
    'northern mariana islands': 'MNP',
    'mozambique': 'MOZ',
    'mauritania': 'MRT',
    'mauritius': 'MUS',
    'malawi': 'MWI',
    'malaysia': 'MYS',
    'north america': 'NAC',
    'namibia': 'NAM',
    'new caledonia': 'NCL',
    'niger': 'NER',
    'nigeria': 'NGA',
    'nicaragua': 'NIC',
    'niue': 'NIU',
    'netherlands': 'NLD',
    'high income: nonoecd': 'NOC',
    'norfolk island': 'NFK',
    'norway': 'NOR',
    'nepal': 'NPL',
    'nauru': 'NRU',
    'new zealand': 'NZL',
    'high income: oecd': 'OEC',
    'oecd members': 'OED',
    'oman': 'OMN',
    'other small states': 'OSS',
    'pakistan': 'PAK',
    'panama': 'PAN',
    'pitcairn islands': 'PCN',
    'peru': 'PER',
    'philippines': 'PHL',
    'palau': 'PLW',
    'papua new guinea': 'PNG',
    'poland': 'POL',
    'puerto rico': 'PRI',
    'korea, dem. rep.': 'PRK',
    'democratic people\'s republic of korea': 'PRK',
    'portugal': 'PRT',
    'paraguay': 'PRY',
    'pacific island small states': 'PSS',
    'french polynesia': 'PYF',
    'qatar': 'QAT',
    'romania': 'ROU',
    'russian federation': 'RUS',
    'rwanda': 'RWA',
    'south asia': 'SAS',
    'saudi arabia': 'SAU',
    'saudi arabia, middle income group': 'SAU',
    'saudi arabia, all cities': 'SAU',
    'the former state union serbia and montenegro': 'SCG',
    'serbia and montenegro': 'SCG',
    'sudan': 'SDN',
    'senegal': 'SEN',
    'singapore': 'SGP',
    'solomon islands': 'SLB',
    'sierra leone': 'SLE',
    'el salvador': 'SLV',
    'san marino': 'SMR',
    'somalia': 'SOM',
    'serbia': 'SRB',
    'sub-saharan africa (developing only)': 'SSA',
    'south sudan': 'SSD',
    'sub-saharan africa (all income levels)': 'SSF',
    'small states': 'SST',
    'sao tome and principe': 'STP',
    'suriname': 'SUR',
    'slovak republic': 'SVK',
    'slovakia': 'SVK',
    'slovenia': 'SVN',
    'sweden': 'SWE',
    'swaziland': 'SWZ',
    'sint maarten (dutch part)': 'SXM',
    'sint maarten (dutch part)': 'SXM',
    'seychelles': 'SYC',
    'svalbard and jan mayen islands': 'SJM',
    'svalbard and jan mayen': 'SJM',
    'syrian arab republic': 'SYR',
    'ussr': 'SUN',
    'turks and caicos islands': 'TCA',
    'chad': 'TCD',
    'togo': 'TGO',
    'thailand': 'THA',
    'tajikistan': 'TJK',
    'tokelau': 'TKL',
    'turkmenistan': 'TKM',
    'timor-leste': 'TLS',
    'tonga': 'TON',
    'trinidad and tobago': 'TTO',
    'tunisia': 'TUN',
    'turkey': 'TUR',
    'tuvalu': 'TUV',
    'china, taiwan province of': 'TWN',
    'tanzania': 'TZA',
    'united republic of tanzania': 'TZA',
    'uganda': 'UGA',
    'ukraine': 'UKR',
    'upper middle income': 'UMC',
    'uruguay': 'URY',
    'united states': 'USA',
    'united states of america': 'USA',
    'uzbekistan': 'UZB',
    'st. vincent and the grenadines': 'VCT',
    'saint vincent and the grenadines': 'VCT',
    'venezuela, rb': 'VEN',
    'venezuela (bolivarian republic of)': 'VEN',
    'virgin islands (u.s.)': 'VIR',
    'united states virgin islands': 'VIR',
    'vietnam': 'VNM',
    'viet nam': 'VNM',
    'vanuatu': 'VUT',
    'west bank and gaza': 'PSE',
    'occupied palestinian territory': 'PSE',
    'palestine, state of': 'PSE',
    'gaza strip (palestine)': 'PSE',
    'world': 'WLD',
    'samoa': 'WSM',
    'yemen, rep.': 'YEM',
    'yemen ar rp': 'YEM',
    'yemen': 'YEM',
    'yemen dem': 'YEM',
    'south africa': 'ZAF',
    'congo, dem. rep.': 'COD',
    'zambia': 'ZMB',
    'zambia, low income group': 'ZMB',
    'zimbabwe': 'ZWE',
    'holy see': 'VAT',
    'martinique': 'MTQ',
    'mayotte': 'MYT',
    'montserrat': 'MSR',
    'netherlands antilles (former)': 'ANT',
    'netherlands antilles': 'ANT',
    u'r\u017dunion': 'REU',
    'r\xe9union': 'REU',
    'r\xc3\xa9union': 'REU',
    'saint helena, ascension and tristan da cunha': 'TAA',
    'saint pierre and miquelon': 'SPM',
    'sudan (former)': 'SDN',
    'the former yugoslav republic of macedonia': 'MKD',
    'british virgin islands': 'VIR',
    'wallis and futuna islands': 'WLF',
    'yugoslav sfr': 'YUG',
    'west bank and gaza strip': 'PSE',
    'wake island': 'WAK',
    'western sahara': 'ESH'
}

cities = [

]

regions = [
    'solomon islands, honiara',
    'central african republic, bangui',
    'guinea, conakry',
    'falkland islands (malvinas), stanley',
    'guinea, conakry',
    'chile, santiago',
    'saint kitts and nevis, saint kitts',
    'south sudan, funafuti',
    'namibia, windhoek',
    'cook islands, rarotonga',
    'nicaragua, managua',
    'india, urban non-manual employees',
    'sri lanka, colombo',
    'kiribati, tarawa',
    'cambodia, phnom penh',
    'marshall islands, majuro',
    'rwanda, kigali',
    'togo, lome',
    'saint-martin (french part)',
    'congo, brazzaville',
    'guinea-bissau, bissau',
    'united republic of tanzania, zanzibar',
    'panama, panama',
    'india, industrial workers',
    'niger, niamey',
    'myanmar, yangon',
    'uruguay, montevideo',
    'madagascar, antananarivo',
    'mali, bamako',
    'argentina, buenos aires',
    'sierra leone, freetown',
    "c\xc3\xb4te d'ivoire, abidjan",
    "chad, n'djamena",
    'venezuela (bolivarian republic of), caracas',
    'new caledonia, noumea',
    'kenya, nairobi',
    'india, agricultural workers',
    'northern mariana islands, saipan',
    'madagascar, antananarivo, europ.',
    'mozambique, maputo',
    'gambia, banjul',
    'maldives, male',
    'mongolia, ulan bator',
    'senegal, dakar',
    'saint vincent and the grenadines, saint vincent',
    'india, delhi, industrial workers',
    'paraguay, asuncion',
    'angola, luanda',
    'malaysia, sabah',
    'ethiopia, addis abeba',
    'lebanon, beyrouth',
    'syrian arab republic, damas',
    'cape verde, praia',
    'suriname, paramaribo',
    'united republic of tanzania, tanganyika',
    'oman, muscat',
    'gabon, libreville',
    'swaziland, mbabane-manzini',
    'equatorial guinea, malabo',
    'guyana, georgetown',
    'benin, cotonou',
    'brazil, sao paulo',
    'burkina faso, ouagadougou',
    'bahamas, new providence',
    'burundi, bujumbura',
    'peru, lima'
]

excluded_countries = [
    u'country',
    u'developing countries',
    u'africa',
    u'eastern africa',
    u'middle africa',
    u'southern africa',
    u'western africa',
    u'north africa (exc sudan)',
    u'sub-saharan africa',
    u'asia',
    u'caucasus and central asia',
    u'east asia',
    u'east asia (exc china)',
    u'southern asia',
    u'south asia (exc india)',
    u'south-eastern asia',
    u'west asia',
    u'central america',
    u'south america',
    u'latin america and the caribbean',
    u'caribbean',
    u'latin america',
    u'oceania',
    u'developed countries'
    u'least developed countries',
    u'land locked developing countries',
    u'small island developing states',
    u'low income economies',
    u'lower-middle-income economies',
    u'low income food deficit countries',
    u'developed countries',
    u'least developed countries',
    'low income economies',
    'south-eastern asia',
    'developing countries',
    'eastern africa',
    'northern africa',
    'middle africa + (total)',
    'small island developing states',
    'sub-saharan africa',
    'oceania + (total)',
    'eastern europe + (total)',
    'annex i countries',
    'polynesia + (total)',
    'western asia',
    'melanesia',
    'latin america',
    'western africa + (total)',
    'americas + (total)',
    'eu(27)ex.int',
    'micronesia + (total)',
    'southern asia + (total)',
    'least developed countries',
    'least developed countries + (total)',
    'north africa (exc sudan)',
    'european union (exc intra-trade)',
    'central america + (total)',
    'caribbean + (total)',
    'western europe + (total)',
    'northern america',
    'land locked developing countries + (total)',
    'landlocked developing countries + (total)',
    'southern asia',
    'asia + (total)',
    'east asia',
    'french southern and antarctic territories',
    'northern europe',
    'land locked developing countries',
    'net food importing developing countries + (total)',
    'asia',
    'western africa',
    'caucasus and central asia',
    'central asia + (total)',
    'central asia',
    'africa + (total)',
    'europe',
    'eu(25)ex.int',
    'world + (total)',
    'antarctic region',
    'small island developing states + (total)',
    'low income food deficit countries + (total)',
    'eastern asia + (total)',
    'latin america and the caribbean',
    'south asia (exc india)',
    'south-eastern asia + (total)',
    'polynesia',
    'non-annex i countries',
    'eu(15)ex.int',
    'developed countries',
    'melanesia + (total)',
    'northern america + (total)',
    'west asia',
    'western asia + (total)',
    'africa',
    'eastern europe',
    'southern africa + (total)',
    'european union + (total)',
    'middle africa',
    'micronesia',
    'antarctica',
    'eastern asia',
    'germany nl',
    'southern europe + (total)',
    'australia and new zealand + (total)',
    'southern africa',
    'northern africa + (total)',
    'lower-middle-income economies',
    'northern europe + (total)',
    'low income food deficit countries',
    'americas',
    'south america + (total)',
    'eu(12)ex.int',
    'central america',
    'pacific islands trust territory',
    'eastern africa + (total)',
    'net food importing developing countries',
    'oecd',
    'europe + (total)',
    'western europe',
    'east asia (exc china)',
    'australia & new zealand',
    'south america',
    'oceania',
    'caribbean',
    'southern europe',
    'belgium-luxembourg',
    'australia & new zealand + (total)',
]

path = '/Volumes/WD_disk/FAOSTAT/'
headers = {
    'ASTI_Research_Spending_E_All_Data_(Norm).csv': ["Country Code", "Country", "Item Code", "Item", "Element Code", "Element", "Year Code", "Year", "Unit", "Value", "Flag"],
    'ASTI_Researchers_E_All_Data_(Norm).csv': ["Country Code", "Country", "Item Code", "Item", "Element Code", "Element", "Year Code", "Year", "Unit", "Value", "Flag"],
    'CommodityBalances_Crops_E_All_Data_(Norm).csv': ["Country Code", "Country", "Item Code", "Item", "Element Code", "Element", "Year Code", "Year", "Unit", "Value", "Flag"],
    'CommodityBalances_LivestockFish_E_All_Data_(Norm).csv': ["Country Code", "Country", "Item Code", "Item", "Element Code", "Element", "Year Code", "Year", "Unit", "Value", "Flag"],
    'ConsumerPriceIndices_E_All_Data_(Norm).csv': ["Country Code", "Country", "Item Code", "Item", "Months Code", "Months", "Year Code", "Year", "Unit", "Value", "Flag", "Note"],
    'Deflators_E_All_Data_(Norm).csv': ["Country Code", "Country", "Item Code", "Item", "Element Code", "Element", "Year Code", "Year", "Unit", "Value", "Flag"],
    'Emissions_Agriculture_Agriculture_total_E_All_Data_(Norm).csv': ["Country Code", "Country", "Item Code", "Item", "Element Code", "Element", "Year Code", "Year", "Unit", "Value", "Flag"],
    'Emissions_Agriculture_Burning_Savanna_E_All_Data_(Norm).csv': ["Country Code", "Country", "Item Code", "Item", "Element Code", "Element", "Year Code", "Year", "Unit", "Value", "Flag"],
    'Emissions_Agriculture_Burning_crop_residues_E_All_Data_(Norm).csv': ["Country Code", "Country", "Item Code", "Item", "Element Code", "Element", "Year Code", "Year", "Unit", "Value", "Flag"],
    'Emissions_Agriculture_Crop_Residues_E_All_Data_(Norm).csv': ["Country Code", "Country", "Item Code", "Item", "Element Code", "Element", "Year Code", "Year", "Unit", "Value", "Flag"],
    'Emissions_Agriculture_Cultivated_Organic_Soils_E_All_Data_(Norm).csv': ["Country Code", "Country", "Item Code", "Item", "Element Code", "Element", "Year Code", "Year", "Unit", "Value", "Flag"],
    'Emissions_Agriculture_Energy_E_All_Data_(Norm).csv': ["Country Code", "Country", "Item Code", "Item", "Element Code", "Element", "Year Code", "Year", "Unit", "Value", "Flag"],
    'Emissions_Agriculture_Enteric_Fermentation_E_All_Data_(Norm).csv': ["Country Code", "Country", "Item Code", "Item", "Element Code", "Element", "Year Code", "Year", "Unit", "Value", "Flag"],
    'Emissions_Agriculture_Manure_Management_E_All_Data_(Norm).csv': ["Country Code", "Country", "Item Code", "Item", "Element Code", "Element", "Year Code", "Year", "Unit", "Value", "Flag"],
    'Emissions_Agriculture_Manure_applied_to_soils_E_All_Data_(Norm).csv': ["Country Code", "Country", "Item Code", "Item", "Element Code", "Element", "Year Code", "Year", "Unit", "Value", "Flag"],
    'Emissions_Agriculture_Manure_left_on_pasture_E_All_Data_(Norm).csv': ["Country Code", "Country", "Item Code", "Item", "Element Code", "Element", "Year Code", "Year", "Unit", "Value", "Flag"],
    'Emissions_Agriculture_Rice_Cultivation_E_All_Data_(Norm).csv': ["Country Code", "Country", "Item Code", "Item", "Element Code", "Element", "Year Code", "Year", "Unit", "Value", "Flag"],
    'Emissions_Agriculture_Synthetic_Fertilizers_E_All_Data_(Norm).csv': ["Country Code", "Country", "Item Code", "Item", "Element Code", "Element", "Year Code", "Year", "Unit", "Value", "Flag"],
    'Emissions_Land_Use_Burning_Biomass_E_All_Data_(Norm).csv': ["Country Code", "Country", "Item Code", "Item", "Element Code", "Element", "Year Code", "Year", "Unit", "Value", "Flag"],
    'Emissions_Land_Use_Cropland_E_All_Data_(Norm).csv': ["Country Code", "Country", "Item Code", "Item", "Element Code", "Element", "Year Code", "Year", "Unit", "Value", "Flag"],
    'Emissions_Land_Use_Forest_Land_E_All_Data_(Norm).csv': ["Country Code", "Country", "Item Code", "Item", "Element Code", "Element", "Year Code", "Year", "Unit", "Value", "Flag"],
    'Emissions_Land_Use_Grassland_E_All_Data_(Norm).csv': ["Country Code", "Country", "Item Code", "Item", "Element Code", "Element", "Year Code", "Year", "Unit", "Value", "Flag"],
    'Emissions_Land_Use_Land_Use_Total_E_All_Data_(Norm).csv': ["Country Code", "Country", "Item Code", "Item", "Element Code", "Element", "Year Code", "Year", "Unit", "Value", "Flag"],
    'Employment_Indicators_E_All_Data_(Norm).csv': ["Country Code", "Country", "Source Code", "Source", "Indicator Code", "Indicator", "Year Code", "Year", "Unit", "Value", "Flag"],
    'Environment_AirClimateChange_E_All_Data.csv': ["CountryCode", "Country", "ItemCode", "Item", "ElementGroup", "ElementCode", "Element", "Year", "Unit", "Value", "Flag"],
    'Environment_Energy_E_All_Data.csv': ["CountryCode", "Country", "ItemCode", "Item", "ElementGroup", "ElementCode", "Element", "Year", "Unit", "Value", "Flag"],
    'Environment_Fertilizers_E_All_Data.csv': ["CountryCode", "Country", "ItemCode", "Item", "ElementGroup", "ElementCode", "Element", "Year", "Unit", "Value", "Flag"],
    'Environment_Land_E_All_Data.csv': ["CountryCode", "Country", "ItemCode", "Item", "ElementGroup", "ElementCode", "Element", "Year", "Unit", "Value", "Flag"],
    'Environment_Livestock_E_All_Data.csv': ["CountryCode", "Country", "ItemCode", "Item", "ElementGroup", "ElementCode", "Element", "Year", "Unit", "Value", "Flag"],
    'Environment_Pesticides_E_All_Data.csv': ["CountryCode", "Country", "ItemCode", "Item", "ElementGroup", "ElementCode", "Element", "Year", "Unit", "Value", "Flag"],
    'Environment_Soil_E_All_Data.csv': ["CountryCode", "Country", "ItemCode", "Item", "ElementGroup", "ElementCode", "Element", "Year", "Unit", "Value", "Flag"],
    'Environment_Water_E_All_Data.csv': ["CountryCode", "Country", "ItemCode", "Item", "ElementGroup", "ElementCode", "Element", "Year", "Unit", "Value", "Flag"],
    'FoodBalanceSheets_E_All_Data_(Norm).csv': ["Country Code", "Country", "Item Code", "Item", "Element Code", "Element", "Year Code", "Year", "Unit", "Value", "Flag"],
    'FoodSupply_Crops_E_All_Data_(Norm).csv': ["Country Code", "Country", "Item Code", "Item", "Element Code", "Element", "Year Code", "Year", "Unit", "Value", "Flag"],
    'FoodSupply_LivestockFish_E_All_Data_(Norm).csv': ["Country Code", "Country", "Item Code", "Item", "Element Code", "Element", "Year Code", "Year", "Unit", "Value", "Flag"],
    # 'Food_Aid_Shipments_WFP_E_All_Data_(Norm).csv': ["Recipient Country Code", "Recipient Country", "Item Code", "Item", "Donor Country Code", "Donor Country", "Year Code", "Year", "Unit", "Value", "Flag"],
    'Food_Security_Data_E_All_Data_(Norm).csv': ["Country Code", "Country", "Item Code", "Item", "Element Code", "Element", "Year Code", "Year", "Unit", "Value", "Flag"],
    'Forestry_E_All_Data_(Norm).csv': ["Country Code", "Country", "Item Code", "Item", "Element Code", "Element", "Year Code", "Year", "Unit", "Value", "Flag"],
    # 'Forestry_Trade_Flows_E_All_Data_(Norm).csv': ["Reporter Country Code", "Reporter Countries", "Partner Country Code", "Partner Countries", "Item Code", "Item", "Element Code", "Element", "Year Code", "Year", "Unit", "Value", "Flag"],
    'Inputs_FertilizersTradeValues_E_All_Data_(Norm).csv': ["Country Code", "Country", "Item Code", "Item", "Element Code", "Element", "Year Code", "Year", "Unit", "Value", "Flag"],
    'Inputs_Fertilizers_E_All_Data_(Norm).csv': ["Country Code", "Country", "Item Code", "Item", "Element Code", "Element", "Year Code", "Year", "Unit", "Value", "Flag"],
    'Inputs_Land_E_All_Data_(Norm).csv': ["Country Code", "Country", "Item Code", "Item", "Element Code", "Element", "Year Code", "Year", "Unit", "Value", "Flag"],
    'Inputs_Pesticides_Trade_E_All_Data_(Norm).csv': ["Country Code", "Country", "Item Code", "Item", "Element Code", "Element", "Year Code", "Year", "Unit", "Value", "Flag"],
    'Inputs_Pesticides_Use_E_All_Data_(Norm).csv': ["Country Code", "Country", "Item Code", "Item", "Element Code", "Element", "Year Code", "Year", "Unit", "Value", "Flag"],
    'Investment_CapitalStock_E_All_Data.csv': ["CountryCode", "Country", "ItemCode", "Item", "ElementGroup", "ElementCode", "Element", "Year", "Unit", "Value", "Flag"],
    'Investment_CreditAgriculture_E_All_Data_(Norm).csv': ["Country Code", "Country", "Item Code", "Item", "Element Code", "Element", "Year Code", "Year", "Unit", "Value", "Flag"],
    'Investment_GovernmentExpenditure_E_All_Data_(Norm).csv': ["Country Code", "Country", "Item Code", "Item", "Element Code", "Element", "Year Code", "Year", "Unit", "Value", "Flag"],
    'Investment_MachineryArchive_E_All_Data.csv': ["CountryCode", "Country", "ItemCode", "Item", "ElementGroup", "ElementCode", "Element", "Year", "Unit", "Value", "Flag"],
    'Investment_Machinery_E_All_Data.csv': ["CountryCode", "Country", "ItemCode", "Item", "ElementGroup", "ElementCode", "Element", "Year", "Unit", "Value", "Flag"],
    'Macro-Statistics_Key_Indicators_E_All_Data_(Norm).csv': ["Country Code", "Country", "Item Code", "Item", "Element Code", "Element", "Year Code", "Year", "Unit", "Value", "Flag"],
    'Population_E_All_Data_(Norm).csv': ["Country Code", "Country", "Item Code", "Item", "Element Code", "Element", "Year Code", "Year", "Unit", "Value", "Flag"],
    'Price_Indices_E_All_Data_(Norm).csv': ["Country Code", "Country", "Item Code", "Item", "Element Code", "Element", "Year Code", "Year", "Unit", "Value", "Flag"],
    'PricesArchive_E_All_Data.csv': ["CountryCode", "Country", "ItemCode", "Item", "ElementGroup", "ElementCode", "Element", "Year", "Unit", "Value", "Flag"],
    'Prices_E_All_Data_(Norm).csv': ["Country Code", "Country", "Item Code", "Item", "Element Code", "Element", "Year Code", "Year", "Unit", "Value", "Flag"],
    'Prices_Monthly_E_All_Data_(Norm).csv': ["Country Code", "Country", "Item Code", "Item", "Months Code", "Months", "Year Code", "Year", "Unit", "Value", "Flag"],
    'Production_CropsProcessed_E_All_Data_(Norm).csv': ["Country Code", "Country", "Item Code", "Item", "Element Code", "Element", "Year Code", "Year", "Unit", "Value", "Flag"],
    'Production_Crops_E_All_Data_(Norm).csv': ["Country Code", "Country", "Item Code", "Item", "Element Code", "Element", "Year Code", "Year", "Unit", "Value", "Flag"],
    'Production_Indices_E_All_Data_(Norm).csv': ["Country Code", "Country", "Item Code", "Item", "Element Code", "Element", "Year Code", "Year", "Unit", "Value", "Flag"],
    'Production_LivestockPrimary_E_All_Data_(Norm).csv': ["Country Code", "Country", "Item Code", "Item", "Element Code", "Element", "Year Code", "Year", "Unit", "Value", "Flag"],
    'Production_LivestockProcessed_E_All_Data_(Norm).csv': ["Country Code", "Country", "Item Code", "Item", "Element Code", "Element", "Year Code", "Year", "Unit", "Value", "Flag"],
    'Production_Livestock_E_All_Data_(Norm).csv': ["Country Code", "Country", "Item Code", "Item", "Element Code", "Element", "Year Code", "Year", "Unit", "Value", "Flag"],
    'Resources_FertilizersArchive_E_All_Data.csv': ["CountryCode", "Country", "ItemCode", "Item", "ElementGroup", "ElementCode", "Element", "Year", "Unit", "Value", "Flag"],
    'Trade_Crops_Livestock_E_All_Data_(Norm).csv': ["Country Code", "Country", "Item Code", "Item", "Element Code", "Element", "Year Code", "Year", "Unit", "Value", "Flag"],
    # 'Trade_DetailedTradeMatrix_E_All_Data_(Norm).csv': ["Reporter Country Code", "Reporter Countries", "Partner Country Code", "Partner Countries", "Item Code", "Item", "Element Code", "Element", "Year Code", "Year", "Unit", "Value", "Flag"],
    'Trade_Indices_E_All_Data_(Norm).csv': ["Country Code", "Country", "Item Code", "Item", "Element Code", "Element", "Year Code", "Year", "Unit", "Value", "Flag"],
    'Trade_LiveAnimals_E_All_Data_(Norm).csv': ["Country Code", "Country", "Item Code", "Item", "Element Code", "Element", "Year Code", "Year", "Unit", "Value", "Flag"],
    'Value_of_Production_E_All_Data_(Norm).csv': ["Country Code", "Country", "Item Code", "Item", "Element Code", "Element", "Year Code", "Year", "Unit", "Value", "Flag"]
}

def parse_countries():
    client = MongoClient('mongodb://192.168.99.100:5999/')
    db = client['topodb']
    collection = db.FAO_countries
    collection_domains = db.FAO_domains
    collection_elements = db.FAO_elements
    mongo_data = []
    attributes = {}
    elements = Set()
    fao_domains = []
    for filename in os.listdir(path):
        print filename
        if filename.split('.')[1] != 'csv':
            continue
        with open(path + filename) as f:
            reader = csv.DictReader(f, fieldnames=headers[filename])
            first = True
            fao_domains.append({'Domain': filename.split('.')[0]})
            for row in reader:
                entry = {}
                if first or row[headers[filename][1]].lower().decode('latin-1').encode('utf-8') in excluded_countries or row[headers[filename][1]].lower().decode('latin-1').encode('utf-8') in regions:
                    first = False
                    continue
                sys.stdout.write('Country: ' + country_code[row[headers[filename][1]].lower().decode('latin-1').encode('utf-8')] + '\r')
                date_index = headers[filename].index('Year')
                entry = row
                for attr in entry:
                    entry[attr] = entry[attr].decode('latin-1').encode('utf-8')
                country_index = headers[filename].index('Country')
                entry['Domain'] = filename.split('.')[0]
                entry['Country ID'] = country_code[row[headers[filename][country_index]].lower()]
                if '-' in row[headers[filename][7]]:
                    dates = range(int(row[headers[filename][date_index]].split(
                        '-')[0]), int(row[headers[filename][date_index]].split('-')[1]))
                    for year in dates:
                        entry['Date'] = year
                        try:
                            entry['Country'] = entry['Country']
                        except:
                            print entry['Country']
                        collection.insert_one(entry)
                        # try:
                        #     entry = {
                        #         'Country ID': country_code[row[headers[filename][1]]],
                        #         'Date': year,
                        #         'Domain': filename.split('.')[0],
                        #         'Item': if headers[filename][3] == 'Partner Countries': row[headers[filename][3]],
                        #         'Element': '',
                        #         'Unit': row[headers[filename][8]],
                        #         'Value': row[headers[filename][9]]
                        #     }
                        # except:
                        #     elements.add(row[headers[filename][1]])
                else:
                    entry['Date'] = row[headers[filename][date_index]]
                    try:
                        entry['Country'] = entry['Country']
                    except:
                        print entry['Country']
                    collection.insert_one(entry)
                    # try:
                    #     entry = {
                    #         'Country ID': country_code[row[headers[filename][1]]],
                    #         'Date': row[headers[filename][7]],
                    #         'Domain': filename.split('.')[0],
                    #         'Item': row[headers[filename][3]],
                    #         'Element': '',
                    #         'Unit': row[headers[filename][8]],
                    #         'Value': row[headers[filename][9]]
                    #     }
                    # except:
                    #     elements.add(row[headers[filename][1]])
                # print row
                # print row[headers[filename][3]]
                # elements.add(row[headers[filename][3]])
                # print headers[filename][5], row[headers[filename][5]]
                # break
            # break
        # pprint.pprint(elements)
    collection_domains.insert_many(fao_domains)
    # json_data = json.load(f)
    # Each entry represents a country + Attribute for several years
    # for entry in json_data:
    #     if entry['Country'] not in country_code and entry['Country'] not in excluded:
    #         pprint.pprint(entry['Country'])
    #     pprint.pprint(entry)
    #     if entry["ID"] not in attributes:
    #         try:
    #             attributes[entry["ID"]] = entry["Item"]
    #         except:
    #             attributes[entry["ID"]] = filename
    # f.close()
    # break
# print attributes
# for country in data:
#     for year in data[country]:
#         entry = {}
#         entry['id'] = country
#         try:
#             entry['name'] = [i for i in country_code if country_code[i] == country][0]
#         except:
#             continue
#         entry['date'] = year
#         entry['attrs'] = {}
#         for attr in data[country][year]:
#             new_attr = attr.replace('.', '-')
#             sys.stdout.write('Country: ' + entry['id'] + ' # '+ attr + '\r')
#             entry['attrs'][new_attr] = data[country][year][attr]
#         mongo_data.append(entry)
#         # Push to mongodb!
#         # collection.insert_one(entry)
#
# g = open('attr_data/WDI/WDI_csv/WDIJSON.json', 'w')
# g.write(json.dumps(mongo_data))
# g.close()
parse_countries()
